sugarcube-2:
  macros:
    dialogelement:
      name: dialogelement
      container: true
      children:
      - "onopen"
      - "onclose"
    dialogelementclose:
      name: dialogelementclose
    onopen:
      name: onopen
    onclose:
      name: onclose