sugarcube-2:
  macros:
    dialogelement:
      name: dialogelement
      container: true
    dialogelementclose:
      name: dialogelementclose
    opendialogelement:
      name: opendialogelement
      container: true
      parameters: 
      - "text"
